server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cowrie
    static_configs:
      - targets:
          - localhost
        labels:
          job: cowrie
          __path__: /var/log/cowrie/cowrie.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000Z07:00"

  - job_name: opencanary
    static_configs:
      - targets:
          - localhost
        labels:
          job: opencanary
          __path__: /var/log/opencanary/opencanary.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: utc_time
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000000"
