server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cowrie
    static_configs:
      - targets:
          - localhost
        labels:
          job: cowrie
          __path__: /var/log/cowrie/cowrie.json

  - job_name: opencanary
    static_configs:
      - targets:
          - localhost
        labels:
          job: opencanary
          __path__: /var/log/opencanary/opencanary.log
